# Generated by Django 5.2.1 on 2025-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSismico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('profundidad', models.FloatField(blank=True, null=True)),
                ('magnitud_mw', models.FloatField(blank=True, null=True)),
                ('magnitud_mb', models.FloatField(blank=True, null=True)),
                ('magnitud_ms', models.FloatField(blank=True, null=True)),
                ('scalar_moment', models.CharField(blank=True, max_length=50, null=True)),
                ('strike1', models.FloatField(blank=True, null=True)),
                ('dip1', models.FloatField(blank=True, null=True)),
                ('slip1', models.FloatField(blank=True, null=True)),
                ('strike2', models.FloatField(blank=True, null=True)),
                ('dip2', models.FloatField(blank=True, null=True)),
                ('slip2', models.FloatField(blank=True, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
